### ISSUE TITLE
[BUG] <Lua Error>

### ISSUE THREAD

**Issue by lyubenpeev** [GoldpawsStuff/AzeriteUI5#38] opened 2023-07-12 22:51 UTC
### Game Flavor

Classic Era

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/GoldpawsStuff/AzeriteUI5/assets/116773837/e242b3e0-2355-44c2-b5a0-ae4e59040437)
Lua error

### To reproduce

log in

### Expected behavior

latest update on game and addon

### Screenshots

![image](https://github.com/GoldpawsStuff/AzeriteUI5/assets/116773837/f322f8cf-766e-41a3-8ecf-a517bfb2eb82)

### Additional context

Thank you for all your efforts. Not all heroes wear capes.

**Comment by Goldpaw** [comment] 2023-07-13 09:32
I have my doubts that this is an AzeriteUI error. 

It backtracks from AzeriteUI hiding the GameTooltip, that is correct, but the actual error says that the global function `type` is no longer a function, but a string value. AzeriteUI does no such thing. I've search through every single file in the whole UI. At no point does it replace the `type` function.

Any addon could replace that function, but the bug occurs only when somebody tries to call it. Which happens quite often, and I bet a lot of those 11 errors in the bug tracker is about the `type` function.

**Comment by Goldpaw** [comment] 2023-07-13 09:34
Does it happen with ONLY AzeriteUI and no other addon enabled?

**Comment by lyubenpeev** [comment] 2023-07-13 22:30
yes, it does happen with only azerite and no other addons. Do you think this is something I could fix on my end then?

**Comment by lyubenpeev** [comment] 2023-07-21 02:06
Is it possible I'd need to install Retail WoW.. Load the Addon on there and then install it on Classic, or that doesn't matter?

**Comment by Goldpaw** [comment] 2023-07-22 13:24
No. Doesn't matter at all.

**Comment by Goldpaw** [comment] 2023-07-26 18:55
As an update I have gotten this bug reported from other sources too, and by typing `/dumb issecurevariable("type")` in the chat, we tracked it to apparently being AzeriteUI which replaces it. 

Which just makes no sense, beceause it doesn't. I have searched the entire folder including all its libraries for any way that could possiby happen. None. Nothing. Also, I can't reproduce this bug myself in any way shape or form. 

So I'm sort of clueless at this point. But I continue searching.

**Comment by lyubenpeev** [comment] 2023-07-26 18:57
Thanks buddy, I really appreciate you doing this. Yeah, it’s surprising..
because I’ve tried everything (as a non-programmer) I could do

**Comment by Goldpaw** [comment] 2023-07-27 08:23
Progress! I can reproduce it now on Classic Era PTR (Hardcore)! 

Won't be long until I can pinpoint it and fix it then! :)

![Screenshot from 2023-07-27 10-22-27](https://github.com/GoldpawsStuff/AzeriteUI5/assets/6476535/629237a8-985d-40d4-9fdc-f5c04724b456)

**Comment by Goldpaw** [comment] 2023-07-27 08:38
Issue was in the vanilla tracker module. Found and fixed in 5.2.90-RC, which I just uploaded to Curse/Wago and should be available shortly! Yaaay!

**Closed by Goldpaw** 2023-07-27 08:38 UTC
Labels: bug

**Comment by lyubenpeev** [comment] 2023-07-27 10:50
Hell yeah!!
