### ISSUE TITLE
[BUG] Profiles not saving and reverting to default with a reload of the UI or logging in

### ISSUE THREAD

**Issue by anaarkei** [GoldpawsStuff/AzeriteUI5#28] opened 2023-06-17 01:41 UTC
### Game Flavor

Dragonflight

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Making changes in the options menu or in the frames manager does not save. When reloading the UI or logging back into the game, everything is reset to the default settings. This happens regardless of making changes to the default profile, creating a new profile, or duplicating a profile. Any profile created is also lost when reloading or logging out, requiring manual changes to be made every time a reload or logout occurs.

### To reproduce

Make changes or create a new profile. Reload the UI or log out and log back in.

### Expected behavior

Settings and profiles should save on reload or game exit.

### Additional context

None

**Comment by Billybishop** [comment] 2023-06-17 06:28
Potentially related to #29

**Comment by Combobulates** [comment] 2023-06-17 09:41
I can confirm. Just updated version. If I modify changes and reload/log out they revery to default. The new az profiles I create are not saved. Also action bars, map, player frames - nothing is appearing in the WOW EDIT mode anymore. Am I missing something?

**Comment by Goldpaw** [comment] 2023-06-17 11:44
> I can confirm. Just updated version. If I modify changes and reload/log out they revery to default. The new az profiles I create are not saved. Also action bars, map, player frames - nothing is appearing in the WOW EDIT mode anymore. Am I missing something?
> 
> I also get an error when sliding line bars sometimes.

Please don't post several questions and issues as replies to a post about another issue. 

It is intentional that the edit mode and our own movable frames no longer are connected. They are two completely different systems, and the screen was horrible crowded and cluttered when both where visible at once. We have our `/lock` mode now in 5.1, and it applies to all versions of the game. 

I am unable to reproduce any profiling bugs in the latest **tagged** version from CurseForge, which is 5.1.68-Release. That is not to say that it hasn't got bugs, but I cannot currently reproduce them. If you used one of the two prior versions from today and yesterday, please try a `/resetsettings` to see if that can fix the problem. This fully resets AzeriteUIs settings to its defaults. Does not affect anything else than AzeriteUI.

Available chat commands can be found at: 
https://github.com/GoldpawsStuff/AzeriteUI5#readme

**Comment by Billybishop** [comment] 2023-06-17 22:57
> > I can confirm. Just updated version. If I modify changes and reload/log out they revery to default. The new az profiles I create are not saved. Also action bars, map, player frames - nothing is appearing in the WOW EDIT mode anymore. Am I missing something?
> > I also get an error when sliding line bars sometimes.
> 
> Please don't post several questions and issues as replies to a post about another issue.
> 
> It is intentional that the edit mode and our own movable frames no longer are connected. They are two completely different systems, and the screen was horrible crowded and cluttered when both where visible at once. We have our `/lock` mode now in 5.1, and it applies to all versions of the game.
> 
> I am unable to reproduce any profiling bugs in the latest **tagged** version from CurseForge, which is 5.1.68-Release. That is not to say that it hasn't got bugs, but I cannot currently reproduce them. If you used one of the two prior versions from today and yesterday, please try a `/resetsettings` to see if that can fix the problem. This fully resets AzeriteUIs settings to its defaults. Does not affect anything else than AzeriteUI.
> 
> Available chat commands can be found at: https://github.com/GoldpawsStuff/AzeriteUI5#readme

I can also confirm that this bug is present in the current release. I've tried the latest 3 tags (5.1.68-release being the latest). Tried deleting cache and wtf, tried resetsettings each time.  Profiles and frame positions or scales no longer saving on for me on retail, it will always reset to default.

**Comment by Goldpaw** [comment] 2023-06-18 13:56
Fixed in 5.1.69-Release.

**Closed by Goldpaw** 2023-06-18 13:56 UTC
Labels: bug
